# Use the official MongoDB image as the base image (Ubuntu)
FROM mongo:latest

# Set environment variables to enhance security (Default Credentials just for validation)
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=strongPassword123

# CIS Benchmark Recommendations for default configuration
RUN mkdir -p /etc/mongod \
    && chown -R mongodb:mongodb /etc/mongod \
    && chmod -R 700 /etc/mongod

# Update Ubuntu base Image
RUN apt-get -y update
RUN apt-get -y upgrade

RUN set -eux; \
	apt-get update; \
	apt-get install -y gosu; \
	rm -rf /var/lib/apt/lists/*; \
    rm -rf /usr/local/bin/gosu/*; \
# verify that the binary works
	gosu nobody true

# Copy MongoDB configuration file to the container
COPY mongod.conf /etc/mongod/mongod.conf

# Expose MongoDB default port
EXPOSE 27017

# Start MongoDB service

CMD ["mongod", "--config", "/etc/mongod/mongod.conf"]