version: '3'

services:
  mongodb:
    build: .
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=strongPassword123
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge