name: trivy-ci-checks
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  trivy-ci-checks:
    name: trivy-ci-checks
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        scan-ref: '.'
        trivy-config: trivy-ci-checks.yml